version: '3.8'
services:
  api:
    build: 
      context: .
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
    ports: 
      - '3000:3000'
    networks: 
      - backend
    volumes: 
      - ./src:/home/node/api/src
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    networks: 
      - backend
    volumes:
      - ./.docker/mysql/db:/var/lib/mysql
      - ./.docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
networks: 
  backend:
    driver: bridge